# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7z020clg484-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Users/AhmedAli/Documents/GP- Chest X Ray/chest X Ray/chest X Ray.cache/wt} [current_project]
set_property parent.project_path {C:/Users/AhmedAli/Documents/GP- Chest X Ray/chest X Ray/chest X Ray.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo {c:/Users/AhmedAli/Documents/GP- Chest X Ray/chest X Ray/chest X Ray.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib -sv {
  C:/Users/AhmedAli/Desktop/bneck/bneck/AdaptiveAvgPool2d_1x1.sv
  C:/Users/AhmedAli/Desktop/bneck/bneck/BatchNorm_se.sv
  C:/Users/AhmedAli/Desktop/bneck/bneck/BottleNeck_11Stage_Sequential_Optimized.sv
  C:/Users/AhmedAli/Desktop/bneck/bneck/BottleNeck_Optimized.sv
  C:/Users/AhmedAli/Desktop/bneck/bneck/BottleNeck_const_func.sv
  C:/Users/AhmedAli/Desktop/bneck/bneck/Conv2D.sv
  {C:/Users/AhmedAli/Documents/GP- Chest X Ray/First Layer/HSwish.sv}
  C:/Users/AhmedAli/Desktop/bneck/bneck/HardSwishSigmoid.sv
  C:/Users/AhmedAli/Desktop/bneck/bneck/ReLU_se.sv
  C:/Users/AhmedAli/Desktop/bneck/bneck/SE_module.sv
  {C:/Users/AhmedAli/Documents/GP- Chest X Ray/First Layer/accelerator.sv}
  {C:/Users/AhmedAli/Documents/GP- Chest X Ray/Final layer/batchnorm.sv}
  {C:/Users/AhmedAli/Documents/GP- Chest X Ray/Final layer/batchnorm1d.sv}
  {C:/Users/AhmedAli/Documents/GP- Chest X Ray/First Layer/convolver.sv}
  {C:/Users/AhmedAli/Documents/GP- Chest X Ray/dsp_resource_manager.sv}
  {C:/Users/AhmedAli/Documents/GP- Chest X Ray/external_memory_controller.sv}
  {C:/Users/AhmedAli/Documents/GP- Chest X Ray/Final layer/final_layer_top.sv}
  {C:/Users/AhmedAli/Documents/GP- Chest X Ray/Final layer/hswish.sv}
  {C:/Users/AhmedAli/Documents/GP- Chest X Ray/interface_adapter.sv}
  {C:/Users/AhmedAli/Documents/GP- Chest X Ray/Final layer/linear_external_weights.sv}
  {C:/Users/AhmedAli/Documents/GP- Chest X Ray/Final layer/pointwise_conv.sv}
  C:/Users/AhmedAli/Desktop/bneck/bneck/shortcut_with_actual_modules.sv
  {C:/Users/AhmedAli/Documents/GP- Chest X Ray/weight_memory_manager.sv}
  {C:/Users/AhmedAli/Documents/GP- Chest X Ray/chest_xray_classifier_top.sv}
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top chest_xray_classifier_top -part xc7z020clg484-2


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef chest_xray_classifier_top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file chest_xray_classifier_top_utilization_synth.rpt -pb chest_xray_classifier_top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
